#!/bin/zsh

# ===============================================================================================
# FZF
# ===============================================================================================

# Setup fzf
# ---------
if [[ ! "$PATH" == */Users/codycallahan/.fzf/bin* ]]; then
  export PATH="$PATH:/Users/codycallahan/.fzf/bin"
fi

# Man path
# --------
if [[ ! "$MANPATH" == */Users/codycallahan/.fzf/man* && -d "/Users/codycallahan/.fzf/man" ]]; then
  export MANPATH="$MANPATH:/Users/codycallahan/.fzf/man"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "/Users/codycallahan/.fzf/shell/completion.zsh" 2> /dev/null

# Key bindings
# ------------
source "/Users/codycallahan/.fzf/shell/key-bindings.zsh"

# fzf Completion
export FZF_COMPLETION_TRIGGER='**'
bindkey '^T' fzf-completion
bindkey '^I' $fzf_default_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
